// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8cObINJDnhwRabOrcqqF7I7xIjlc09dM',
    appId: '1:996092510410:web:b23eca99e8b92d07bbb433',
    messagingSenderId: '996092510410',
    projectId: 'unisync-dev-5d925',
    authDomain: 'unisync-dev-5d925.firebaseapp.com',
    storageBucket: 'unisync-dev-5d925.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-aC2102724cKmoT-2r0AKFeIGpf7FKQ',
    appId: '1:996092510410:android:7b1b98e2a62fbd6abbb433',
    messagingSenderId: '996092510410',
    projectId: 'unisync-dev-5d925',
    storageBucket: 'unisync-dev-5d925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_5wEToN0vy7T23V8p0PvX-Teo3Kwv0Dc',
    appId: '1:996092510410:ios:5d7e0643ad82079ebbb433',
    messagingSenderId: '996092510410',
    projectId: 'unisync-dev-5d925',
    storageBucket: 'unisync-dev-5d925.firebasestorage.app',
    iosBundleId: 'com.example.unisync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_5wEToN0vy7T23V8p0PvX-Teo3Kwv0Dc',
    appId: '1:996092510410:ios:5d7e0643ad82079ebbb433',
    messagingSenderId: '996092510410',
    projectId: 'unisync-dev-5d925',
    storageBucket: 'unisync-dev-5d925.firebasestorage.app',
    iosBundleId: 'com.example.unisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8cObINJDnhwRabOrcqqF7I7xIjlc09dM',
    appId: '1:996092510410:web:400f2b12e3b01182bbb433',
    messagingSenderId: '996092510410',
    projectId: 'unisync-dev-5d925',
    authDomain: 'unisync-dev-5d925.firebaseapp.com',
    storageBucket: 'unisync-dev-5d925.firebasestorage.app',
  );
}
